services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - app-network
    volumes:
      - mongodata:/data/db

  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11457571/assess1:latest
    container_name: app
    networks:
      - app-network
    volumes:
      - uploaddata:/app/upload
      - outputdata:/app/output
    environment:
      PORT: 3000
      TOKEN_SECRET: 6CfVaNSaHLzOp545zlh6
      TOKEN_EXPIRATION: 30d
      UPLOAD_MAXSIZE: 52428800
      MONGODB_URI: mongodb://mongo:27017
    ports:
      - "80:3000"
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
  uploaddata:
  outputdata:
